Mission7/Components/CategoryViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;

namespace Mission7.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public CategoryViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            var categories = repo.Books
                .Select(c => c.Category)
                .Distinct()
                .OrderBy(c => c);

            return View(categories);
        }
    }
}

Mission7/Views/Shared/Components/CartSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;
namespace Mission7.Views.Shared.Components
{
    public class CartSummaryViewComponent :ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart c)
        {
            cart = c;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Mission7/Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Books

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4 style="font-family:Chivo">
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right; font-family:Crimson Pro">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1" style="font-family:Crimson Pro">
        Author: @Model.Author<br />Publisher: @Model.Publisher<br />
        ISBN: @Model.ISBN<br />Classification: @Model.Classification<br />
        Category: @Model.Category<br />Number of Pages: @Model.PageCount
    </div>

    <form method="post" asp-page="/Buy">
        <input type="hidden" asp-for="@Model.BookID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Buy</button>
        </span>
    </form>
</div>

Mission7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Little Corner Bookstore</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Chivo:wght@300&family=Crimson+Pro&display=swap" rel="stylesheet">
    <link href="~/lib/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <span class="col navbar-brand ml-2" style="font-family:Chivo">Little Corner Bookstore</span>
                <div class="col-6 text-right">
                    <vc:cart-summary></vc:cart-summary>
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3" style="font-family:Chivo">
            <vc:category></vc:category>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>