Mission7/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mission7.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }

        private Cart cart { get; set; }

        public PurchaseController(IPurchaseRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Looks like your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.ClearCart();

                return RedirectToPage("/PurchaseCompleted");
            }

            else
            {
                return View();
            }
        }
    }
}

Mission7/Pages/Buy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission7.Infrastructure;
using Mission7.Models;

namespace Mission7.Pages
{
    public class BuyModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public Cart cart { get; set; }

        public string ReturnUrl { get; set; }

        public BuyModel (IBookstoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(b => b.BookID == bookId);

            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostDelete(int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(b => b.Books.BookID == bookId).Books);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Mission7/Pages/Buy.cshtml
@page
@model Mission7.Pages.BuyModel
@{
}

<h2>Your Basket</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price Per Book</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.cart.Items)
        {
            <tr>
                <td style="font-family:Crimson Pro">@i.Books.Title</td>
                <td style="font-family:Crimson Pro">@i.Quantity</td>
                <td style="font-family:Crimson Pro">@i.Price.ToString("c")</td>
                <td style="font-family:Crimson Pro">@((i.Quantity * i.Price).ToString("c"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Delete">
                        <input type="hidden" name="bookId" value="@i.Books.BookID" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger" style="font-family:Chivo">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" style="font-family:Crimson Pro">Total:</td>
            @*"c" formats it to currency*@
            <td style="font-family:Crimson Pro">@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl" style="font-family:Chivo">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase" style="font-family:Chivo">Checkout</a>
</div>

Mission7/Pages/PurchaseCompleted.cshtml
@page
@{
}

<div class="text-center">
    <h2 style="font-family:Chivo">Order Sucessfully Placed</h2>
    <p style="font-family:Crimson Pro">Watch your email for shipping information.</p>
    <h3 style="font-family:Chivo">Thanks for your order!</h3>
    <a class="btn btn-primary" asp-controller="Home" style="font-family:Chivo">Return Home</a>
</div>

Mission7/Pages/_BuyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Chivo:wght@300&family=Crimson+Pro&display=swap" rel="stylesheet">
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2" style="font-family:Chivo">Little Corner Bookstore</span>
    </div>
    <div class="row m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>